# Generated by Django 3.2.3 on 2024-01-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20240117_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Изображение рецепта', upload_to='recipes/media/', verbose_name='Изображение рецепта'),
        ),
    ]
